# Must have REST CLIENT vsCode estension installed
# Comments
### Seperate HTTP Requests
# Content-Type application/json

# Click on "Send Request" to acctivate HTTP Call

# GET/TEST
GET http://localhost:3001/crops


### GET Plant Test
GET http://www.growstuff.org/crops/avocado.json

### POST
POST http://localhost:3001/crops
Content-Type: application/json

{
  "name": "Frank",
  "description": "I like cats"
}

### PUT
PUT http://localhost:3001/
Content-Type: application/json

{
  "name":"Updated stuff"
}

###
DELETE http://localhost:3001/crops/618df64abd98b50d673475e9



# HEROKU
### TEST
GET 